Repository GEOS-ESM/GEOSradiation_GridComp, pull requests merged in 2022-12, with the labels that each got.

#11 Move to use GitHub Action for Label Enforcement
  .github/workflows/enforce-labels.yml
Labels: 0 diff, 0 diff structural

#10 Feature/pnorris/#9 add obio exports for chou suarez as well
  GEOSsolar_GridComp/GEOS_SolarGridComp.F90
  GEOSsolar_GridComp/sorad.F90
Labels: 0 diff

#14 pmn: added vrtqdr code explanations, 0-diff
  GEOSsolar_GridComp/RRTMG/rrtmg_sw/gcm_model/src/rrtmg_sw_spcvmc.F90
Labels: 0 diff trivial
